version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: file_upload_api/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - upload_network
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 8G
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/data/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    sysctls:
      - net.ipv4.tcp_keepalive_time=60
      - net.ipv4.tcp_keepalive_intvl=10
      - net.ipv4.tcp_keepalive_probes=6

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "5000-5005:5000"
    environment:
      - API_URL=http://api:8000
      - REQUESTS_TIMEOUT=30
      - MAX_RETRIES=3
      - RETRY_BACKOFF=5
    networks:
      - upload_network
    deploy:
      replicas: 6
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 2G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    depends_on:
      api:
        condition: service_healthy
    mem_swappiness: 0
    mem_reservation: 2G
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

networks:
  upload_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16 