version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: file_upload_api/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - upload_network
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 8G
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    expose:
      - "5000"
    networks:
      - upload_network
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "5000-5005:5000-5005"
    networks:
      - upload_network
    depends_on:
      - client

networks:
  upload_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16 