version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: file_upload_api/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - upload_network
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 8G
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/data/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "9000-9005:5000"
    networks:
      - upload_network
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api

networks:
  upload_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16 